### ISSUE TITLE
Record viewer expects two-channel WAV files

### ISSUE THREAD

**Issue by er-nun-vogelfrei-ist** [MLAB-project/pysdr#7]
Feeding a standard mono-channel WAV file will make numpy extremely unhappy:

```
Traceback (most recent call last):
  File "./pysdr-recviewer", line 5, in <module>
    main()
  File ".../pysdr/recviewer.py", line 168, in main
    sample_rate, signal = read_file(sys.argv[1])
  File ".../pysdr/recviewer.py", line 145, in read_file
    return (sample_rate, audio[:,0] + 1j * audio[:,1])
IndexError: too many indices
```

And converting a mono-channel WAV to two channels will produce unreliable results depending on the tool. If both channels contain the same samples, the resulting spectrogram will be an incorrect representation of the signal.

**Comment by kaklik** [comment]
We always have two channel complex data eg. I and Q so we do not work with mono wav files. Working with wav mono data the same as I/Q data stream with identical channels.
